### ISSUE TITLE
Disabling the Blue Crosshair in the Magnifier

### ISSUE THREAD

**Issue by Raulzus** [Upload/ShareX#1]
I love this program but I've been getting annoyed by the blue crosshair in the magnifier because it makes it difficult to do precise selections since it obstructs pixels.

Example: http://i.imgur.com/tlytFLR.png

Is there any way to disable it or do you plan on adding a way to do so?

**Comment by k3d3** [comment]
This is no longer the official Up1 ShareX distribution; we've since been included into the main ShareX. It might be better to ask there.
